### ISSUE TITLE
Whirlwind tutorial 

### ISSUE THREAD

**Issue by BitBait** [sourcebots/docs#116]
In the section "Using functions effectively ":
The I looks like a 1, at least on my computer. 
(https://imgur.com/Ni2HQbr)

Also in the section "Average calculator":
There is a piece of text that says input is like input? (kier suggested this was because this was originally a python2 tutorial and raw_input was similar to input). Also we should introduce int/float(input()) or introduce converting input into int or float so that the code can be averaged. 

Also there are no solutions, (i don't think these are hard problems but sometimes attempting the same problem over and over again can be really annoying).

**Comment by RealOrangeOne** [comment]
> The I looks like a 1
This is due to the font. However, integers are highlighted in red in this highlighter, so it should be obvious enough which it is.

Sounds like I changed `raw_input` without checking the surrounding sentence, woops! That's an issue

The fact there are no solutions is ok, we walk them through the code and how to do things.

(There's 3 issues in here, which becomes really difficult to track. Raising 3 seperate issues, 3 trello tickets, or fixing some yourself and raising the rest greatly helps)

**Comment by kierdavis** [comment]
I'll split this up into three separate issues and close this one shortly.

**Comment by kierdavis** [comment]
Closing in favour of #118, #119 and #120.
