### ISSUE TITLE
Good Sportsmanship

### ISSUE THREAD

**Issue by tpoomlmly** [sourcebots/docs#158]
https://github.com/sourcebots/docs/blob/master/content/faqs/_index.md

IIRC this was changed to a gender-neutral alternative in the SP2020 rulebook, so I think it should be changed here too

(Also is there really only 1 question people frequently ask? I guess it is the 1st question everyone asks me when I tell them about SRO but there must be more)

**Comment by jefftheprogrammer** [comment]
We need to think of more questions

**Comment by tpoomlmly** [comment]
I can't find the 2020 rules online, but I've got a copy in my drawer which I'll look at when I get back to Southampton

**Comment by RealOrangeOne** [comment]
The FAQs aren't in the rules. They existed because people kept asking questions. If people don't ask them, then they're not frequently asked. For smallpiece, we could get away with removing this section, if not, let's just fix the 1 word from this issue and then get on with the rest of what needs doing.
